In [1]:
import pandas as pd
import tensorflow as tf
import numpy as np
import gc
import time
#import matplotlib.pyplot as plt
#from livelossplot.keras import PlotLossesCallback
from tensorflow.keras.callbacks import ReduceLROnPlateau
from keras.models import load_model

Using TensorFlow backend.

In [99]:
data_train=pd.read_csv('traindata20200520.csv',header=0,encoding='gbk')
data_train

,Vegetation,QH_DEM,QH_Aspect,QH_Slope,GPP2019169,GPP2019177,GPP2019185,GPP2019193,GPP2019201,GPP2019209,...,SR20192575,SR20192576,SR20192577,SR20192651,SR20192652,SR20192653,SR20192654,SR20192655,SR20192656,SR20192657
0,小嵩草、垂穗披碱草草甸,3740,251.813995,31.240200,250,81,293,229,327,279,...,2452,1585,761,761,2471,379,677,3086,2213,1100
1,小嵩草、垂穗披碱草草甸,3740,251.813995,31.240200,250,81,293,229,327,279,...,2452,1585,761,761,2471,379,677,3086,2213,1100
2,小嵩草、垂穗披碱草草甸,3755,289.044006,24.078699,239,81,298,223,328,279,...,2484,1637,821,772,2445,391,684,3092,2226,1107
3,小嵩草、垂穗披碱草草甸,3755,289.044006,24.078699,239,81,298,223,328,279,...,2484,1637,821,772,2445,391,684,3092,2226,1107
4,小嵩草、垂穗披碱草草甸,3785,275.941986,28.350700,246,81,295,230,327,278,...,2511,1651,836,766,2435,391,683,3083,2213,1098
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2899,西北针茅草原,4193,135.093002,3.394220,109,40,139,113,160,127,...,4587,3712,2496,1473,2760,716,1152,3664,3333,2339
2900,西北针茅草原,4200,233.194000,9.060290,122,41,144,116,173,134,...,4596,3734,2471,1417,2745,694,1113,3635,3259,2211
2901,西北针茅草原,4200,233.194000,9.060290,122,41,144,116,173,134,...,4596,3734,2471,1417,2745,694,1113,3635,3259,2211
2902,西北针茅草原,4193,310.510010,4.988270,133,44,149,120,185,140,...,4509,3645,2401,1415,2747,692,1112,3636,3261,2211
2903,西北针茅草原,4193,310.510010,4.988270,133,44,149,120,185,140,...,4509,3645,2401,1415,2747,692,1112,3636,3261,2211

In [68]:
data_train.info()
data_train.Vegetation.unique()
#len(data_train.Vegetation.unique())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2904 entries, 0 to 2903
Columns: 163 entries, Vegetation to SR20192657
dtypes: float64(6), int64(156), object(1)
memory usage: 3.6+ MB

array(['小嵩草、垂穗披碱草草甸', '线叶嵩草、珠芽蓼、圆穗蓼草甸', '金露梅灌丛', '线叶嵩草草甸', '小嵩草草甸',
       '垫状金露梅灌丛', '藏嵩草沼泽化草甸', '高山嵩草草甸', '嵩草草甸', '垂穗披碱草草甸', '芨芨草草甸',
       '高山嵩草、异针茅草原化草甸', '矮生嵩草草甸', '冰草、紫花针茅草原', '线叶嵩草-紫花针茅草甸', '紫花针茅草原',
       '短花针茅草原', '藏北嵩草沼泽草甸', '芨芨草草原', '赖草草甸', '长芒草、赖草、猪毛蒿草原', '沙生针茅草原',
       '矮生嵩草、紫花针茅草甸', '华扁穗草沼泽草甸', '矮生嵩草、紫花针茅草原化草甸', '藏嵩草沼泽草甸',
       '小嵩草、黄帚橐吾草甸', '小嵩草、青海刺参、黄帚橐吾草甸', '鹅绒委陵菜、青海刺参草甸', '黄帚橐吾、圆穗蓼草甸',
       '珠芽蓼、圆穗蓼草甸', '小嵩草、珠芽蓼、圆穗蓼草甸', '矮嵩草、垂穗披碱草草甸', '小嵩草、黄帚橐吾、圆穗蓼草甸',
       '小嵩草、白苞筋骨草草甸', '高山流石坡稀疏植被', '青藏苔草、藏嵩草草原', '早熟禾、细叶西伯利亚蓼、海乳草草原',
       '小嵩草、早熟禾草原化草甸', '披针叶黄华、细叶亚菊草原', '冷蒿草原', '匍匐水柏枝与嵩草草甸复合体',
       '小嵩草、矮嵩草草甸', '藏西风毛菊、细叶亚菊草原', '异针茅草原', '异针茅、垫状点地梅草原', '异针茅、青海早熟禾草原',
       '异针茅、臭蒿草原', '长芒草草原', '小嵩草、异针茅草原化草甸', '三芒草草甸', '山生柳灌丛', '苔草草甸',
       '细叶亚菊草原化草甸', '疏花针茅草原', '青海早熟禾、扇穗茅草甸', '驼绒藜荒漠', '披碱草草甸', '西藏嵩草沼泽草甸',
       '线叶嵩草、紫花针茅草原化草甸', '高山草甸', '蒿叶猪毛菜砾漠', '矮生嵩草', '高山苔草草原', '苔草、藏嵩草草甸',
       '头花杜鹃灌丛', '鹅绒委陵菜草甸', '冰岛蓼草甸', '黑穗苔草草甸', '小嵩草-紫花针茅草原化草甸', '重齿风毛菊草甸',
       '小嵩草草原化草甸', '矮嵩草-紫花针茅草原化草甸', '小嵩草-异针茅草原化草甸', '青藏苔草草原',
       '冰草、垂穗披碱草草原', '青藏苔草、矮嵩草草甸', '小嵩草、青藏苔草草甸', '青海早熟禾草甸', '西北针茅草原',
       '小嵩草、西北针茅草原化草甸', '小嵩草、紫花针茅草原化草甸', '矮嵩草草甸', '线叶嵩草、青海早熟禾草甸',
       '甘肃雪灵芝、垫状点地梅、簇生柔籽草垫状植被', '细叶亚菊草原'], dtype=object)

In [105]:
pd.set_option('display.max_rows', None)
print(data_train['Vegetation'].value_counts())

矮生嵩草草甸                   355
小嵩草草甸                    274
高山嵩草草甸                   182
长芒草、赖草、猪毛蒿草原             177
垂穗披碱草草甸                  145
芨芨草草原                    124
线叶嵩草草甸                   120
紫花针茅草原                    89
金露梅灌丛                     78
冷蒿草原                      70
异针茅草原                     69
线叶嵩草、珠芽蓼、圆穗蓼草甸            64
小嵩草-紫花针茅草原化草甸             47
青海早熟禾、扇穗茅草甸               46
小嵩草、青海刺参、黄帚橐吾草甸           44
藏嵩草沼泽化草甸                  41
青海早熟禾草甸                   41
西北针茅草原                    40
青藏苔草草原                    40
矮生嵩草、紫花针茅草原化草甸            33
嵩草草甸                      30
小嵩草、西北针茅草原化草甸             30
青藏苔草、矮嵩草草甸                30
矮嵩草草甸                     30
小嵩草、矮嵩草草甸                 30
芨芨草草甸                     29
华扁穗草沼泽草甸                  27
垫状金露梅灌丛                   26
矮生嵩草、紫花针茅草甸               24
赖草草甸                      21
小嵩草、早熟禾草原化草甸              20
珠芽蓼、圆穗蓼草甸                 20
鹅绒委陵菜草甸                   20
藏嵩草沼泽草甸                   20
小嵩草、紫花针茅草原化草甸             20
小嵩草、珠芽蓼、圆穗蓼草甸             20
异针茅、青海早熟禾草原               20
匍匐水柏枝与嵩草草甸复合体             19
短花针茅草原                    15
矮嵩草-紫花针茅草原化草甸             13
细叶亚菊草原                    12
小嵩草、黄帚橐吾草甸                11
小嵩草、青藏苔草草甸                10
高山流石坡稀疏植被                 10
小嵩草、黄帚橐吾、圆穗蓼草甸            10
黄帚橐吾、圆穗蓼草甸                10
早熟禾、细叶西伯利亚蓼、海乳草草原         10
小嵩草、白苞筋骨草草甸               10
小嵩草、异针茅草原化草甸              10
线叶嵩草、青海早熟禾草甸              10
小嵩草-异针茅草原化草甸              10
长芒草草原                     10
异针茅、臭蒿草原                  10
高山草甸                      10
藏西风毛菊、细叶亚菊草原              10
三芒草草甸                     10
小嵩草、垂穗披碱草草甸               10
山生柳灌丛                     10
冰草、垂穗披碱草草原                10
细叶亚菊草原化草甸                 10
异针茅、垫状点地梅草原               10
青藏苔草、藏嵩草草原                10
甘肃雪灵芝、垫状点地梅、簇生柔籽草垫状植被     10
苔草草甸                      10
疏花针茅草原                     9
冰草、紫花针茅草原                  9
西藏嵩草沼泽草甸                   9
驼绒藜荒漠                      8
线叶嵩草、紫花针茅草原化草甸             8
披碱草草甸                      8
矮嵩草、垂穗披碱草草甸                8
黑穗苔草草甸                     7
鹅绒委陵菜、青海刺参草甸               6
线叶嵩草-紫花针茅草甸                5
沙生针茅草原                     5
蒿叶猪毛菜砾漠                    5
高山嵩草、异针茅草原化草甸              5
藏北嵩草沼泽草甸                   5
高山苔草草原                     4
小嵩草草原化草甸                   3
头花杜鹃灌丛                     3
冰岛蓼草甸                      3
苔草、藏嵩草草甸                   3
披针叶黄华、细叶亚菊草原               2
重齿风毛菊草甸                    2
矮生嵩草                       1
Name: Vegetation, dtype: int64

### 顺序编码

In [374]:
# 将其映射到0,1,2...上
class_dict = {'swamp_and_hydrophytic_vegetation':0, 'alpine_steppe':2,
       'alpine_meadow':1, 'temperate_steppe':2, 'meadow':1, 'salt_marsh/swamp':0,
       'semi_shrubby_desert':3, 'shrubby_desert':3, 'dwarf_tree_desert':3,
       'cushion_vegetation':4}
data_train["Vegetation"] = data_train.Vegetation.map(class_dict)
data_train.head()

,Vegetation,DEM,ASPECT,SLOPE,GPP2019169,GPP2019177,GPP2019185,GPP2019193,GPP2019201,GPP2019209,...,PSN2019193,PSN2019201,PSN2019209,PSN2019217,PSN2019225,PSN2019233,PSN2019241,PSN2019249,PSN2019257,PSN2019265
0,0,4298,69.232430,15.326968,208.0,150.0,264.0,248.0,337.0,287.0,...,29787.0,29787.0,29780.0,29780.0,29787.0,29774.0,29783.0,29783.0,29780.0,29782.0
1,2,3403,225.711334,2.215723,87.0,92.0,90.0,110.0,122.0,143.0,...,82.0,99.0,98.0,95.0,72.0,68.0,63.0,58.0,2.0,34.0
2,2,3378,137.565613,2.933709,136.0,138.0,127.0,149.0,169.0,185.0,...,126.0,153.0,170.0,139.0,121.0,99.0,106.0,80.0,3.0,39.0
3,2,3546,210.834885,5.390974,123.0,129.0,144.0,160.0,221.0,193.0,...,147.0,203.0,175.0,142.0,146.0,122.0,102.0,85.0,2.0,50.0
4,0,3767,212.595642,3.668648,112.0,174.0,192.0,212.0,277.0,307.0,...,222.0,259.0,265.0,215.0,218.0,144.0,182.0,114.0,3.0,79.0

### 独热编码

In [69]:
data_train = data_train.join(pd.get_dummies(data_train.Vegetation))
#del data_train["Vegetation"]
data_train.head()

,Vegetation,QH_DEM,QH_Aspect,QH_Slope,GPP2019169,GPP2019177,GPP2019185,GPP2019193,GPP2019201,GPP2019209,...,驼绒藜荒漠,高山嵩草、异针茅草原化草甸,高山嵩草草甸,高山流石坡稀疏植被,高山苔草草原,高山草甸,鹅绒委陵菜、青海刺参草甸,鹅绒委陵菜草甸,黄帚橐吾、圆穗蓼草甸,黑穗苔草草甸
0,小嵩草、垂穗披碱草草甸,3740,251.813995,31.240200,250,81,293,229,327,279,...,0,0,0,0,0,0,0,0,0,0
1,小嵩草、垂穗披碱草草甸,3740,251.813995,31.240200,250,81,293,229,327,279,...,0,0,0,0,0,0,0,0,0,0
2,小嵩草、垂穗披碱草草甸,3755,289.044006,24.078699,239,81,298,223,328,279,...,0,0,0,0,0,0,0,0,0,0
3,小嵩草、垂穗披碱草草甸,3755,289.044006,24.078699,239,81,298,223,328,279,...,0,0,0,0,0,0,0,0,0,0
4,小嵩草、垂穗披碱草草甸,3785,275.941986,28.350700,246,81,295,230,327,278,...,0,0,0,0,0,0,0,0,0,0

### 打乱顺序

In [70]:
# 生成该区间的随意唯一索引
index = np.random.permutation(len(data_train))
# 用生成的乱的索引就能将其打乱了
data_train = data_train.iloc[index ,:]

### 顺序编码的标签

In [376]:
train_x = data_train.iloc[:,1:]
train_y = data_train.loc[:, ['Vegetation']]  
train_x.head(), train_y.head()

(       DEM      ASPECT      SLOPE  GPP2019169  GPP2019177  GPP2019185  \
 514   3377  308.916992   0.490046       163.0        56.0       340.0
 249   3242  146.961166   8.436536       495.0       391.0       528.0
 68    3559  226.310974   8.014600        94.0       265.0       224.0
 764   4529  355.621155   4.955467        28.0        24.0        35.0
 1160  4362   52.506660  20.456871       216.0       211.0       276.0

       GPP2019193  GPP2019201  GPP2019209  GPP2019217  ...  PSN2019193  \
 514        372.0       441.0       361.0       358.0  ...       303.0
 249        622.0       767.0       632.0       671.0  ...       470.0
 68         357.0       311.0       262.0       362.0  ...       309.0
 764         24.0        40.0        42.0        51.0  ...      4179.0
 1160       256.0       366.0       289.0       316.0  ...       204.0

       PSN2019201  PSN2019209  PSN2019217  PSN2019225  PSN2019233  PSN2019241  \
 514        375.0       331.0       302.0       309.0        84.0       253.0
 249        562.0       402.0       462.0       459.0       243.0       363.0
 68         310.0       134.0       307.0       298.0       168.0       215.0
 764       4183.0      4190.0      4186.0      4203.0      4173.0      4183.0
 1160       301.0       227.0       228.0       303.0       298.0       130.0

       PSN2019249  PSN2019257  PSN2019265
 514        195.0         8.0       121.0
 249        328.0         5.0       249.0
 68         169.0         4.0       113.0
 764       4184.0      4156.0      4171.0
 1160       173.0        10.0        72.0

 [5 rows x 158 columns],
       Vegetation
 514            1
 249            1
 68             1
 764            4
 1160           2)

### 独热编码的标签

In [74]:
train_x = data_train.iloc[:, 1:-86]
train_x.head()

,QH_DEM,QH_Aspect,QH_Slope,GPP2019169,GPP2019177,GPP2019185,GPP2019193,GPP2019201,GPP2019209,GPP2019217,...,SR20192575,SR20192576,SR20192577,SR20192651,SR20192652,SR20192653,SR20192654,SR20192655,SR20192656,SR20192657
1079,4615,86.630699,4.897850,146,141,180,102,234,214,225,...,2636,1826,848,870,2265,397,700,3100,2331,1293
1337,4094,87.838699,3.424770,57,18,139,122,170,135,122,...,2625,2266,1447,1333,2411,724,1092,3155,2775,1895
2415,4191,80.212601,46.724602,130,175,184,80,223,207,185,...,4350,3475,1934,1143,2699,536,926,3723,3276,1991
2871,4102,138.281006,7.053000,108,11,95,102,128,104,98,...,2861,2282,1624,1600,2907,818,1281,3719,3408,2547
302,3714,245.317993,10.040000,444,106,335,318,388,363,364,...,3297,2906,1522,940,2648,451,799,3734,3281,1879

In [75]:
train_y = data_train.iloc[:, -86:]
train_y.head()

,三芒草草甸,冰岛蓼草甸,冰草、垂穗披碱草草原,冰草、紫花针茅草原,冷蒿草原,匍匐水柏枝与嵩草草甸复合体,华扁穗草沼泽草甸,垂穗披碱草草甸,垫状金露梅灌丛,头花杜鹃灌丛,...,驼绒藜荒漠,高山嵩草、异针茅草原化草甸,高山嵩草草甸,高山流石坡稀疏植被,高山苔草草原,高山草甸,鹅绒委陵菜、青海刺参草甸,鹅绒委陵菜草甸,黄帚橐吾、圆穗蓼草甸,黑穗苔草草甸
1079,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1337,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2415,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2871,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
302,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [97]:
print(np.argmax(train_y, axis=1))

ValueError: Shape of passed values is (2904, 1), indices imply (2904, 86)

In [117]:
def multi_category_focal_loss1(alpha, gamma=2.0):
    """
    focal loss for multi category of multi label problem
    适用于多分类或多标签问题的focal loss
    alpha用于指定不同类别/标签的权重，数组大小需要与类别个数一致
    当你的数据集不同类别/标签之间存在偏斜，可以尝试适用本函数作为loss
    Usage:
     model.compile(loss=[multi_category_focal_loss1(alpha=[1,2,3,2], gamma=2)], metrics=["accuracy"], optimizer='adam')
    """
    epsilon = 1.e-7
    alpha = tf.constant(alpha, dtype=tf.float32)
    #alpha = tf.constant([[1],[1],[1],[1],[1]], dtype=tf.float32)
    #alpha = tf.constant_initializer(alpha)
    gamma = float(gamma)
    def multi_category_focal_loss1_fixed(y_true, y_pred):
        y_true = tf.cast(y_true, tf.float32)
        y_pred = tf.clip_by_value(y_pred, epsilon, 1. - epsilon)
        y_t = tf.multiply(y_true, y_pred) + tf.multiply(1-y_true, 1-y_pred)
        ce = -tf.math.log(y_t)
        weight = tf.math.pow(tf.subtract(1., y_t), gamma)
        fl = tf.matmul(tf.multiply(weight, ce), alpha)
        loss = tf.reduce_mean(fl)
        return loss
    return multi_category_focal_loss1_fixed

In [236]:
def multi_category_focal_loss2(gamma=2., alpha=.25):
    """
    focal loss for multi category of multi label problem
    适用于多分类或多标签问题的focal loss
    alpha控制真值y_true为1/0时的权重
        1的权重为alpha, 0的权重为1-alpha
    当你的模型欠拟合，学习存在困难时，可以尝试适用本函数作为loss
    当模型过于激进(无论何时总是倾向于预测出1),尝试将alpha调小
    当模型过于惰性(无论何时总是倾向于预测出0,或是某一个固定的常数,说明没有学到有效特征)
        尝试将alpha调大,鼓励模型进行预测出1。
    Usage:
     model.compile(loss=[multi_category_focal_loss2(alpha=0.25, gamma=2)], metrics=["accuracy"], optimizer='adam')
    """
    epsilon = 1.e-7
    gamma = float(gamma)
    alpha = tf.constant(alpha, dtype=tf.float32)

    def multi_category_focal_loss2_fixed(y_true, y_pred):
        y_true = tf.cast(y_true, tf.float32)
        y_pred = tf.clip_by_value(y_pred, epsilon, 1. - epsilon)
    
        alpha_t = y_true*alpha + (tf.ones_like(y_true)-y_true)*(1-alpha)
        y_t = tf.multiply(y_true, y_pred) + tf.multiply(1-y_true, 1-y_pred)
        y_t = tf.clip_by_value(y_t, epsilon, 1. - epsilon)#这句是后加的
        ce = -tf.math.log(y_t)
        weight = tf.math.pow(tf.subtract(1., y_t), gamma)
        fl = tf.multiply(tf.multiply(weight, ce), alpha_t)
        loss = tf.reduce_mean(fl)
        return loss
    return multi_category_focal_loss2_fixed

In [68]:
def focal_loss(pred, y, alpha=0.25, gamma=2):
        r"""Compute focal loss for predictions.
            Multi-labels Focal loss formula:
                FL = -alpha * (z-p)^gamma * log(p) -(1-alpha) * p^gamma * log(1-p)
                     ,which alpha = 0.25, gamma = 2, p = sigmoid(x), z = target_tensor.
        Args:
         pred: A float tensor of shape [batch_size, num_anchors,
            num_classes] representing the predicted logits for each class
         y: A float tensor of shape [batch_size, num_anchors,
            num_classes] representing one-hot encoded classification targets
         alpha: A scalar tensor for focal loss alpha hyper-parameter
         gamma: A scalar tensor for focal loss gamma hyper-parameter
        Returns:
            loss: A (scalar) tensor representing the value of the loss function
        """
        zeros = tf.zeros_like(pred, dtype='float32')
        pred = tf.cast(pred, tf.float32)
        y = tf.cast(y, tf.float32)

        # For positive prediction, only need consider front part loss, back part is 0;
        # target_tensor > zeros <=> z=1, so positive coefficient = z - p.
        pos_p_sub = tf.where(y > zeros, y - pred, zeros) # positive sample 寻找正样本，并进行填充

        # For negative prediction, only need consider back part loss, front part is 0;
        # target_tensor > zeros <=> z=1, so negative coefficient = 0.
        neg_p_sub = tf.where(y > zeros, zeros, pred) # negative sample 寻找负样本，并进行填充
        per_entry_cross_ent = - alpha * (pos_p_sub ** gamma) * tf.math.log(tf.clip_by_value(pred, 1e-8, 1.0)) \
                              - (1 - alpha) * (neg_p_sub ** gamma) * tf.math.log(tf.clip_by_value(1.0 - pred, 1e-8, 1.0))

        return tf.reduce_sum(per_entry_cross_ent)

In [74]:
def focal_loss(y_true, y_pred):
    alpha, gamma = 0.25, 2
    y_pred = tf.clip_by_value(y_pred, 1e-8, 1 - 1e-8)
    loss =  - alpha * y_true * tf.math.log(y_pred) * (1 - y_pred)**gamma\
           - (1 - alpha) * (1 - y_true) * tf.math.log(1 - y_pred) * y_pred**gamma
    return loss

### 顺序编码正确的Focal loss

In [305]:
def focal_loss(y_true, y_pred, alpha=0.25, gamma=2):
    y_true = tf.cast(y_true, tf.float32)
    y_pred = tf.clip_by_value(y_pred, 1e-8, 1 - 1e-8)#避免log出现负值，从而避免loss：nan
    loss = tf.reduce_mean(- tf.reduce_sum(alpha * y_true * tf.math.pow(1-y_pred, gamma) * tf.math.log(y_pred), axis=[1]))
    return loss

In [308]:
def Focal_Loss(y_true, y_pred, alpha=0.25, gamma=2):
    """
    focal loss for multi-class classification
    fl(pt) = -alpha*(1-pt)^(gamma)*log(pt)
    :param y_true: ground truth one-hot vector shape of [batch_size, nb_class]
    :param y_pred: prediction after softmax shape of [batch_size, nb_class]
    :param alpha:
    :param gamma:
    :return:
    """
    # # parameters
    # alpha = 0.25
    # gamma = 2
    y_true = tf.cast(y_true, tf.float32)

    # To avoid divided by zero
    y_pred += tf.keras.backend.epsilon()

    # Cross entropy
    ce = -y_true * tf.math.log(y_pred)

    # Not necessary to multiply y_true(cause it will multiply with CE which has set unconcerned index to zero ),
    # but refer to the definition of p_t, we do it
    weight = tf.math.pow(1 - y_pred, gamma) * y_true

    # Now fl has a shape of [batch_size, nb_class]
    # alpha should be a step function as paper mentioned, but it doesn't matter like reason mentioned above
    # (CE has set unconcerned index to zero)
    #
    # alpha_step = tf.where(y_true, alpha*np.ones_like(y_true), 1-alpha*np.ones_like(y_true))
    fl = ce * weight * alpha

    # Both reduce_sum and reduce_max are ok
    reduce_fl = tf.keras.backend.max(fl, axis=-1)

    return reduce_fl

### 网络构建

In [91]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(1024,input_dim=162))
model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.Dense(512))
model.add(tf.keras.layers.Dense(256))
model.add(tf.keras.layers.Dense(128))
model.add(tf.keras.layers.Dropout(rate=0.5))
model.add(tf.keras.layers.Dense(86, activation='softmax'))
#model.summary()

In [20]:
label_shape=train_y.apply(lambda x:x.sum())
label_shape

三芒草草甸           10
冰岛蓼草甸            3
冰草、垂穗披碱草草原      10
冰草、紫花针茅草原        9
冷蒿草原            70
                ..
高山草甸            10
鹅绒委陵菜、青海刺参草甸     6
鹅绒委陵菜草甸         20
黄帚橐吾、圆穗蓼草甸      10
黑穗苔草草甸           7
Length: 86, dtype: int64

In [402]:
label_shape=[[762],[126],[32],[14],[120],[33],[20],[2],[2],[78]]

In [40]:
# 让学习率自动变化
reduce_lr = ReduceLROnPlateau(monitor='loss',factor=0.1, patience=20, mode='auto')

In [92]:
model.compile(loss='categorical_crossentropy', metrics=['acc'], optimizer='adam')
#顺序编码用loss='sparse_categorical_crossentropy'
#独热编码用loss='categorical_crossentropy'
model.summary()

Model: "sequential_16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_119 (Dense)            (None, 1024)              166912
_________________________________________________________________
batch_normalization_15 (Batc (None, 1024)              4096
_________________________________________________________________
dense_120 (Dense)            (None, 512)               524800
_________________________________________________________________
dense_121 (Dense)            (None, 256)               131328
_________________________________________________________________
dense_122 (Dense)            (None, 128)               32896
_________________________________________________________________
dropout_15 (Dropout)         (None, 128)               0
_________________________________________________________________
dense_123 (Dense)            (None, 86)                11094
=================================================================
Total params: 871,126
Trainable params: 869,078
Non-trainable params: 2,048
_________________________________________________________________

### 开始训练，e = epochs

In [93]:
e = 200
start = time.perf_counter()#time.process_time()测的时间偏长
history = model.fit(train_x,train_y, epochs=e,batch_size=4,verbose=1,callbacks=[reduce_lr])#
mins, secs = divmod((time.perf_counter() - start), 60)
hours, mins = divmod(mins, 60)
print("用时：%02d:%02d:%02d"% (hours, mins, secs))

Train on 2904 samples
Epoch 1/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 8.3581 - acc: 0.1092
Epoch 2/200
2904/2904 [==============================] - 4s 1ms/sample - loss: 4.4483 - acc: 0.1618
Epoch 3/200
2904/2904 [==============================] - 4s 2ms/sample - loss: 3.7165 - acc: 0.1832
Epoch 4/200
2904/2904 [==============================] - 4s 2ms/sample - loss: 3.3524 - acc: 0.2266
Epoch 5/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 3.1800 - acc: 0.2373
Epoch 6/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 3.0554 - acc: 0.2452
Epoch 7/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 2.9608 - acc: 0.2552
Epoch 8/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 2.8363 - acc: 0.2703 1s
Epoch 9/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 2.7804 - acc: 0.2927
Epoch 10/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 2.6820 - acc: 0.3137
Epoch 11/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 2.5937 - acc: 0.3061 - ETA: 0s - loss: 2.5959 - acc: 0.30
Epoch 12/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 2.5088 - acc: 0.3354
Epoch 13/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 2.4557 - acc: 0.3464
Epoch 14/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 2.4090 - acc: 0.3478
Epoch 15/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 2.2861 - acc: 0.3798
Epoch 16/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 2.2595 - acc: 0.3760 1s - loss:
Epoch 17/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 2.1745 - acc: 0.3919
Epoch 18/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 2.0852 - acc: 0.4249
Epoch 19/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 2.0995 - acc: 0.4039
Epoch 20/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 2.0916 - acc: 0.4167 0s - loss: 2.0831 - acc: 0.
Epoch 21/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.9773 - acc: 0.4325
Epoch 22/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.9680 - acc: 0.4446
Epoch 23/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.8850 - acc: 0.4628
Epoch 24/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.8502 - acc: 0.4714 0s - loss: 1.8662
Epoch 25/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.8746 - acc: 0.4659
Epoch 26/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.8361 - acc: 0.4759
Epoch 27/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.8023 - acc: 0.4900
Epoch 28/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.7776 - acc: 0.5000
Epoch 29/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.7685 - acc: 0.4921
Epoch 30/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.7262 - acc: 0.5065
Epoch 31/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.7400 - acc: 0.5017 0s - loss: 1.7433 - acc: 0
Epoch 32/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.6934 - acc: 0.5176
Epoch 33/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.6846 - acc: 0.5079
Epoch 34/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.6474 - acc: 0.5213
Epoch 35/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.6101 - acc: 0.5375 1s - los
Epoch 36/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.5898 - acc: 0.5486
Epoch 37/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.5941 - acc: 0.5451
Epoch 38/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.6034 - acc: 0.5506
Epoch 39/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.5369 - acc: 0.5472
Epoch 40/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.5688 - acc: 0.5437
Epoch 41/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.5492 - acc: 0.5675
Epoch 42/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.5223 - acc: 0.5554
Epoch 43/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.4971 - acc: 0.5665 1s - loss:
Epoch 44/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.5169 - acc: 0.5675 0s - loss: 1.5270 - a
Epoch 45/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.4907 - acc: 0.5682
Epoch 46/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.4700 - acc: 0.5733 1s - loss
Epoch 47/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.4268 - acc: 0.5768
Epoch 48/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.4527 - acc: 0.5895
Epoch 49/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.4434 - acc: 0.5775
Epoch 50/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.4485 - acc: 0.5813 1s
Epoch 51/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.4189 - acc: 0.5782
Epoch 52/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.4402 - acc: 0.5740
Epoch 53/200
2904/2904 [==============================] - 4s 1ms/sample - loss: 1.4423 - acc: 0.5868
Epoch 54/200
2904/2904 [==============================] - 4s 1ms/sample - loss: 1.3632 - acc: 0.5995
Epoch 55/200
2904/2904 [==============================] - 4s 1ms/sample - loss: 1.3670 - acc: 0.5919
Epoch 56/200
2904/2904 [==============================] - 4s 1ms/sample - loss: 1.4080 - acc: 0.5992
Epoch 57/200
2904/2904 [==============================] - 4s 1ms/sample - loss: 1.3399 - acc: 0.6047
Epoch 58/200
2904/2904 [==============================] - 4s 1ms/sample - loss: 1.3719 - acc: 0.5909
Epoch 59/200
2904/2904 [==============================] - 4s 1ms/sample - loss: 1.3652 - acc: 0.6040
Epoch 60/200
2904/2904 [==============================] - 4s 1ms/sample - loss: 1.3042 - acc: 0.6229
Epoch 61/200
2904/2904 [==============================] - 4s 1ms/sample - loss: 1.3537 - acc: 0.6040
Epoch 62/200
2904/2904 [==============================] - 4s 1ms/sample - loss: 1.3427 - acc: 0.6109
Epoch 63/200
2904/2904 [==============================] - 4s 1ms/sample - loss: 1.3484 - acc: 0.6123
Epoch 64/200
2904/2904 [==============================] - 4s 1ms/sample - loss: 1.3224 - acc: 0.6126
Epoch 65/200
2904/2904 [==============================] - 4s 1ms/sample - loss: 1.3393 - acc: 0.6050
Epoch 66/200
2904/2904 [==============================] - 4s 1ms/sample - loss: 1.2739 - acc: 0.6281
Epoch 67/200
2904/2904 [==============================] - 4s 1ms/sample - loss: 1.2836 - acc: 0.6219
Epoch 68/200
2904/2904 [==============================] - 4s 1ms/sample - loss: 1.2897 - acc: 0.6295
Epoch 69/200
2904/2904 [==============================] - 4s 1ms/sample - loss: 1.3225 - acc: 0.6098
Epoch 70/200
2904/2904 [==============================] - 4s 1ms/sample - loss: 1.2709 - acc: 0.6243
Epoch 71/200
2904/2904 [==============================] - 4s 1ms/sample - loss: 1.2308 - acc: 0.6281
Epoch 72/200
2904/2904 [==============================] - 4s 1ms/sample - loss: 1.2256 - acc: 0.6398
Epoch 73/200
2904/2904 [==============================] - 4s 1ms/sample - loss: 1.3064 - acc: 0.6167
Epoch 74/200
2904/2904 [==============================] - 4s 1ms/sample - loss: 1.2571 - acc: 0.6350
Epoch 75/200
2904/2904 [==============================] - 4s 1ms/sample - loss: 1.2451 - acc: 0.6350
Epoch 76/200
2904/2904 [==============================] - 4s 1ms/sample - loss: 1.2754 - acc: 0.6322
Epoch 77/200
2904/2904 [==============================] - 4s 1ms/sample - loss: 1.2444 - acc: 0.6326
Epoch 78/200
2904/2904 [==============================] - 4s 1ms/sample - loss: 1.2010 - acc: 0.6474
Epoch 79/200
2904/2904 [==============================] - 4s 1ms/sample - loss: 1.2615 - acc: 0.6333
Epoch 80/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 1.1794 - acc: 0.6519
Epoch 81/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 1.2037 - acc: 0.6422
Epoch 82/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 1.1904 - acc: 0.6467
Epoch 83/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 1.1805 - acc: 0.6439
Epoch 84/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 1.2100 - acc: 0.6453
Epoch 85/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 1.1772 - acc: 0.6570
Epoch 86/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 1.1769 - acc: 0.6522
Epoch 87/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 1.1538 - acc: 0.6639
Epoch 88/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 1.1997 - acc: 0.6519
Epoch 89/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 1.1903 - acc: 0.6457
Epoch 90/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 1.2088 - acc: 0.6488
Epoch 91/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 1.1419 - acc: 0.6711
Epoch 92/200
2904/2904 [==============================] - 4s 1ms/sample - loss: 1.2192 - acc: 0.6550
Epoch 93/200
2904/2904 [==============================] - 4s 1ms/sample - loss: 1.1120 - acc: 0.6667
Epoch 94/200
2904/2904 [==============================] - 4s 2ms/sample - loss: 1.1885 - acc: 0.6512
Epoch 95/200
2904/2904 [==============================] - 4s 1ms/sample - loss: 1.2196 - acc: 0.6457
Epoch 96/200
2904/2904 [==============================] - 4s 1ms/sample - loss: 1.1528 - acc: 0.6622
Epoch 97/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.1027 - acc: 0.6767
Epoch 98/200
2904/2904 [==============================] - 4s 1ms/sample - loss: 1.1984 - acc: 0.6567
Epoch 99/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.1291 - acc: 0.6705
Epoch 100/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.1214 - acc: 0.6701
Epoch 101/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.1171 - acc: 0.6760
Epoch 102/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.1853 - acc: 0.6581 0s - loss: 1.1951 - acc:
Epoch 103/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.1208 - acc: 0.6811
Epoch 104/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.1294 - acc: 0.6694
Epoch 105/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.1481 - acc: 0.6732
Epoch 106/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.1322 - acc: 0.6711
Epoch 107/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.1416 - acc: 0.6763
Epoch 108/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.1132 - acc: 0.6825
Epoch 109/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.0974 - acc: 0.6760
Epoch 110/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.0607 - acc: 0.6915 0s - loss: 1.0581 - acc: 0.69
Epoch 111/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.1325 - acc: 0.6677
Epoch 112/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.1168 - acc: 0.6756
Epoch 113/200
2904/2904 [==============================] - ETA: 0s - loss: 1.0577 - acc: 0.681 - 6s 2ms/sample - loss: 1.0558 - acc: 0.6811
Epoch 114/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.0852 - acc: 0.6918
Epoch 115/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.1146 - acc: 0.6732
Epoch 116/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.0936 - acc: 0.6877
Epoch 117/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.0889 - acc: 0.6935
Epoch 118/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.0698 - acc: 0.6767
Epoch 119/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.1199 - acc: 0.6760
Epoch 120/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.0414 - acc: 0.6939
Epoch 121/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.1046 - acc: 0.6746
Epoch 122/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.0641 - acc: 0.6921
Epoch 123/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.0340 - acc: 0.7011
Epoch 124/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.0682 - acc: 0.6942
Epoch 125/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.0850 - acc: 0.6928
Epoch 126/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.0633 - acc: 0.6997
Epoch 127/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.0946 - acc: 0.6794
Epoch 128/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.0492 - acc: 0.6935
Epoch 129/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.0310 - acc: 0.6997
Epoch 130/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.0823 - acc: 0.6798
Epoch 131/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.0737 - acc: 0.6887
Epoch 132/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 0.9807 - acc: 0.7083
Epoch 133/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.0741 - acc: 0.6839
Epoch 134/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.0377 - acc: 0.6959
Epoch 135/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.0679 - acc: 0.6921
Epoch 136/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.0161 - acc: 0.7011
Epoch 137/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.0172 - acc: 0.7097
Epoch 138/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.0009 - acc: 0.7176
Epoch 139/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.0309 - acc: 0.7014
Epoch 140/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.0088 - acc: 0.7021
Epoch 141/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.0790 - acc: 0.6956
Epoch 142/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 0.9900 - acc: 0.7039
Epoch 143/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 0.9966 - acc: 0.7187
Epoch 144/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 0.9686 - acc: 0.7221
Epoch 145/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 1.0344 - acc: 0.7083
Epoch 146/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.0371 - acc: 0.7073
Epoch 147/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 0.9677 - acc: 0.7211
Epoch 148/200
2904/2904 [==============================] - 6s 2ms/sample - loss: 0.9837 - acc: 0.7132
Epoch 149/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.0291 - acc: 0.6973
Epoch 150/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 0.9975 - acc: 0.7094
Epoch 151/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 0.9691 - acc: 0.7197
Epoch 152/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.0164 - acc: 0.6987
Epoch 153/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 0.9857 - acc: 0.7197
Epoch 154/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 1.0091 - acc: 0.7070
Epoch 155/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 0.9734 - acc: 0.7149
Epoch 156/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 0.9698 - acc: 0.7176
Epoch 157/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 0.9841 - acc: 0.7218
Epoch 158/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 0.9795 - acc: 0.7200 0s - loss: 0.97
Epoch 159/200

2904/2904 [==============================] - 3s 1ms/sample - loss: 0.9911 - acc: 0.7135
Epoch 160/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 0.9496 - acc: 0.7194
Epoch 161/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 1.0167 - acc: 0.7032
Epoch 162/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 0.9946 - acc: 0.7152
Epoch 163/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 0.9603 - acc: 0.7214
Epoch 164/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 0.9801 - acc: 0.7107
Epoch 165/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 1.0356 - acc: 0.6949
Epoch 166/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 0.9640 - acc: 0.7183
Epoch 167/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 0.9253 - acc: 0.7204
Epoch 168/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 1.0168 - acc: 0.7042
Epoch 169/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 0.9898 - acc: 0.7125
Epoch 170/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 0.9912 - acc: 0.7156
Epoch 171/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 0.9828 - acc: 0.7211
Epoch 172/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 0.9556 - acc: 0.7218
Epoch 173/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 0.9576 - acc: 0.7190
Epoch 174/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 1.0049 - acc: 0.7121
Epoch 175/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 0.9374 - acc: 0.7280
Epoch 176/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 1.0044 - acc: 0.7049
Epoch 177/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 0.9291 - acc: 0.7249
Epoch 178/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 0.9615 - acc: 0.7214
Epoch 179/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 0.9438 - acc: 0.7293
Epoch 180/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 0.9352 - acc: 0.7331
Epoch 181/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 0.9473 - acc: 0.7290
Epoch 182/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 0.9427 - acc: 0.7293
Epoch 183/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 0.9276 - acc: 0.7314
Epoch 184/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 0.9663 - acc: 0.7218
Epoch 185/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 0.9316 - acc: 0.7228
Epoch 186/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 0.9442 - acc: 0.7314
Epoch 187/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 0.9087 - acc: 0.7338
Epoch 188/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 0.9584 - acc: 0.7280
Epoch 189/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 0.9214 - acc: 0.7280
Epoch 190/200
2904/2904 [==============================] - 3s 1ms/sample - loss: 0.9727 - acc: 0.7190
Epoch 191/200
2904/2904 [==============================] - 4s 1ms/sample - loss: 0.9269 - acc: 0.7287
Epoch 192/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 0.9045 - acc: 0.7452
Epoch 193/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 0.9401 - acc: 0.7228
Epoch 194/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 0.8848 - acc: 0.7435
Epoch 195/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 0.9877 - acc: 0.7187
Epoch 196/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 0.9121 - acc: 0.7390
Epoch 197/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 0.9001 - acc: 0.7376
Epoch 198/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 0.9491 - acc: 0.7338
Epoch 199/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 0.8963 - acc: 0.7421
Epoch 200/200
2904/2904 [==============================] - 5s 2ms/sample - loss: 0.9045 - acc: 0.7462
用时：00:15:36

In [ ]:
#plt.plot(range(e),history.history.get('acc'))

In [108]:
#plt.plot(range(e),history.history.get('loss'))

### 储存model

In [94]:
model.save('2020.5.20.model')

INFO:tensorflow:Assets written to: 2020.5.20.model\assets

### 加载model

In [14]:
model = load_model('2020.4.3.model')

OSError: Unable to open file (unable to open file: name = '2020.4.3.model', errno = 13, error message = 'Permission denied', flags = 0, o_flags = 0)

### 清理下内存，不然不够用

In [95]:
gc.collect()

20

In [96]:
def predict(file):
    mylist = []
    index=0
    for chunk in  pd.read_csv(file, chunksize=20000):
        print(index)
        rchunk = pd.DataFrame(model.predict_classes(chunk,verbose=1))
        mylist.append(rchunk)
        index+=1
    temp_df = pd.concat(mylist, axis= 0)
    del mylist
    return temp_df

start = time.process_time()
f = open('testdata20200512.csv')
prediction = predict(f)
np.savetxt("testresult20200520.csv", prediction, fmt="%d",delimiter=",") 
elapsed = (time.process_time() - start)
print("耗时:",time.strftime("%H:%M:%S",elapsed))

0
20000/20000 [==============================] - 1s 58us/sample
1
20000/20000 [==============================] - 1s 49us/sample
2
20000/20000 [==============================] - 1s 50us/sample
3
20000/20000 [==============================] - 1s 50us/sample
4
20000/20000 [==============================] - 1s 52us/sample
5
20000/20000 [==============================] - 1s 52us/sample
6
20000/20000 [==============================] - 1s 54us/sample
7
20000/20000 [==============================] - 1s 54us/sample
8
20000/20000 [==============================] - 1s 52us/sample
9
20000/20000 [==============================] - 1s 54us/sample
10
20000/20000 [==============================] - 1s 54us/sample
11
20000/20000 [==============================] - 1s 54us/sample
12
20000/20000 [==============================] - 1s 55us/sample
13
20000/20000 [==============================] - 1s 55us/sample
14
20000/20000 [==============================] - 1s 56us/sample
15
20000/20000 [==============================] - 1s 55us/sample
16
20000/20000 [==============================] - 1s 55us/sample
17
20000/20000 [==============================] - 1s 55us/sample
18
20000/20000 [==============================] - 1s 54us/sample
19
20000/20000 [==============================] - 1s 55us/sample
20
20000/20000 [==============================] - 1s 56us/sample
21
20000/20000 [==============================] - 1s 55us/sample
22
20000/20000 [==============================] - 1s 54us/sample
23
20000/20000 [==============================] - 1s 55us/sample
24
20000/20000 [==============================] - 1s 55us/sample
25
20000/20000 [==============================] - 1s 55us/sample
26
20000/20000 [==============================] - 1s 55us/sample
27
20000/20000 [==============================] - 1s 56us/sample
28
20000/20000 [==============================] - 1s 56us/sample
29
20000/20000 [==============================] - 1s 55us/sample
30
20000/20000 [==============================] - 1s 54us/sample
31
20000/20000 [==============================] - 1s 56us/sample
32
20000/20000 [==============================] - 1s 56us/sample
33
20000/20000 [==============================] - 1s 55us/sample
34
20000/20000 [==============================] - 1s 55us/sample
35
20000/20000 [==============================] - 1s 56us/sample
36
20000/20000 [==============================] - 1s 56us/sample
37
20000/20000 [==============================] - 1s 55us/sample
38
20000/20000 [==============================] - 1s 56us/sample
39
20000/20000 [==============================] - 1s 55us/sample
40
20000/20000 [==============================] - 1s 56us/sample
41
20000/20000 [==============================] - 1s 58us/sample
42
20000/20000 [==============================] - 1s 57us/sample
43
20000/20000 [==============================] - 1s 57us/sample
44
20000/20000 [==============================] - 1s 56us/sample
45
20000/20000 [==============================] - 1s 55us/sample
46
20000/20000 [==============================] - 1s 55us/sample
47
20000/20000 [==============================] - 1s 55us/sample
48
20000/20000 [==============================] - 1s 55us/sample
49
20000/20000 [==============================] - 1s 55us/sample
50
20000/20000 [==============================] - 1s 56us/sample
51
20000/20000 [==============================] - 1s 56us/sample
52
20000/20000 [==============================] - 1s 56us/sample
53
20000/20000 [==============================] - 1s 53us/sample
54
20000/20000 [==============================] - 1s 53us/sample
55
20000/20000 [==============================] - 1s 53us/sample
56
20000/20000 [==============================] - 1s 53us/sample
57
20000/20000 [==============================] - 1s 53us/sample
58
20000/20000 [==============================] - 1s 52us/sample
59
20000/20000 [==============================] - 1s 53us/sample
60
20000/20000 [==============================] - 1s 52us/sample
61
20000/20000 [==============================] - 1s 57us/sample
62
20000/20000 [==============================] - 1s 53us/sample
63
20000/20000 [==============================] - 1s 50us/sample
64
20000/20000 [==============================] - 1s 49us/sample
65
20000/20000 [==============================] - 1s 49us/sample
66
20000/20000 [==============================] - 1s 49us/sample
67
20000/20000 [==============================] - 1s 49us/sample
68
20000/20000 [==============================] - 1s 49us/sample
69
20000/20000 [==============================] - 1s 49us/sample
70
20000/20000 [==============================] - 1s 48us/sample
71
20000/20000 [==============================] - 1s 49us/sample
72
20000/20000 [==============================] - 1s 48us/sample
73
20000/20000 [==============================] - 1s 50us/sample
74
20000/20000 [==============================] - 1s 48us/sample
75
20000/20000 [==============================] - 1s 49us/sample
76
20000/20000 [==============================] - 1s 48us/sample
77
20000/20000 [==============================] - 1s 49us/sample
78
20000/20000 [==============================] - 1s 49us/sample
79
20000/20000 [==============================] - 1s 49us/sample
80
20000/20000 [==============================] - 1s 48us/sample
81
20000/20000 [==============================] - 1s 48us/sample
82
20000/20000 [==============================] - 1s 49us/sample
83
20000/20000 [==============================] - 1s 50us/sample
84
20000/20000 [==============================] - 1s 49us/sample
85
20000/20000 [==============================] - 1s 49us/sample
86
20000/20000 [==============================] - 1s 48us/sample
87
20000/20000 [==============================] - 1s 50us/sample
88
20000/20000 [==============================] - 1s 49us/sample
89
20000/20000 [==============================] - 1s 48us/sample
90
20000/20000 [==============================] - 1s 49us/sample
91
20000/20000 [==============================] - 1s 49us/sample
92
20000/20000 [==============================] - 1s 48us/sample
93
20000/20000 [==============================] - 1s 48us/sample
94
20000/20000 [==============================] - 1s 50us/sample
95
20000/20000 [==============================] - 1s 49us/sample
96
20000/20000 [==============================] - 1s 48us/sample
97
20000/20000 [==============================] - 1s 49us/sample
98
20000/20000 [==============================] - 1s 48us/sample
99
20000/20000 [==============================] - 1s 49us/sample
100
20000/20000 [==============================] - 1s 49us/sample
101
20000/20000 [==============================] - 1s 49us/sample
102
20000/20000 [==============================] - 1s 49us/sample
103
20000/20000 [==============================] - 1s 50us/sample
104
20000/20000 [==============================] - 1s 49us/sample
105
20000/20000 [==============================] - 1s 48us/sample
106
20000/20000 [==============================] - 1s 49us/sample
107
20000/20000 [==============================] - 1s 48us/sample
108
20000/20000 [==============================] - 1s 48us/sample
109
20000/20000 [==============================] - 1s 49us/sample
110
20000/20000 [==============================] - 1s 48us/sample
111
20000/20000 [==============================] - 1s 48us/sample
112
20000/20000 [==============================] - 1s 49us/sample
113
20000/20000 [==============================] - 1s 49us/sample
114
20000/20000 [==============================] - 1s 49us/sample
115
20000/20000 [==============================] - 1s 49us/sample
116
20000/20000 [==============================] - 1s 48us/sample
117
20000/20000 [==============================] - 1s 49us/sample
118
20000/20000 [==============================] - 1s 50us/sample
119
20000/20000 [==============================] - 1s 49us/sample
120
20000/20000 [==============================] - 1s 48us/sample
121
20000/20000 [==============================] - 1s 48us/sample
122
20000/20000 [==============================] - 1s 48us/sample
123
20000/20000 [==============================] - 1s 49us/sample
124
20000/20000 [==============================] - 1s 49us/sample
125
20000/20000 [==============================] - 1s 44us/sample
126
20000/20000 [==============================] - 1s 44us/sample
127
20000/20000 [==============================] - 1s 44us/sample
128
20000/20000 [==============================] - 1s 43us/sample
129
20000/20000 [==============================] - 1s 43us/sample
130
20000/20000 [==============================] - 1s 44us/sample
131
20000/20000 [==============================] - 1s 43us/sample
132
20000/20000 [==============================] - 1s 45us/sample
133
20000/20000 [==============================] - 1s 50us/sample
134
20000/20000 [==============================] - 1s 49us/sample
135
20000/20000 [==============================] - 1s 60us/sample
136
20000/20000 [==============================] - 1s 54us/sample
137
20000/20000 [==============================] - 1s 54us/sample
138
20000/20000 [==============================] - 1s 53us/sample
139
20000/20000 [==============================] - 1s 54us/sample
140
20000/20000 [==============================] - 1s 53us/sample
141
20000/20000 [==============================] - 1s 54us/sample
142
20000/20000 [==============================] - 1s 52us/sample
143
20000/20000 [==============================] - 1s 53us/sample
144
20000/20000 [==============================] - 1s 52us/sample
145
20000/20000 [==============================] - 1s 54us/sample
146
20000/20000 [==============================] - 1s 52us/sample
147
20000/20000 [==============================] - 1s 54us/sample
148
20000/20000 [==============================] - 1s 52us/sample
149
20000/20000 [==============================] - 1s 53us/sample
150
20000/20000 [==============================] - 1s 53us/sample
151
20000/20000 [==============================] - 1s 53us/sample
152
20000/20000 [==============================] - 1s 53us/sample
153
20000/20000 [==============================] - 1s 53us/sample
154
20000/20000 [==============================] - 1s 54us/sample
155
20000/20000 [==============================] - 1s 53us/sample
156
20000/20000 [==============================] - 1s 54us/sample
157
20000/20000 [==============================] - 1s 53us/sample
158
20000/20000 [==============================] - 1s 52us/sample
159
20000/20000 [==============================] - 1s 53us/sample
160
20000/20000 [==============================] - 1s 55us/sample
161
20000/20000 [==============================] - 1s 53us/sample
162
20000/20000 [==============================] - 1s 53us/sample
163
20000/20000 [==============================] - 1s 52us/sample
164
20000/20000 [==============================] - 1s 54us/sample
165
20000/20000 [==============================] - 1s 53us/sample
166
20000/20000 [==============================] - 1s 54us/sample
167
20000/20000 [==============================] - 1s 54us/sample
168
20000/20000 [==============================] - 1s 53us/sample
169
20000/20000 [==============================] - 1s 54us/sample
170
20000/20000 [==============================] - 1s 52us/sample
171
20000/20000 [==============================] - 1s 53us/sample
172
20000/20000 [==============================] - 1s 54us/sample
173
20000/20000 [==============================] - 1s 54us/sample
174
20000/20000 [==============================] - 1s 52us/sample
175
20000/20000 [==============================] - 1s 54us/sample
176
20000/20000 [==============================] - 1s 54us/sample
177
20000/20000 [==============================] - 1s 53us/sample
178
20000/20000 [==============================] - 1s 53us/sample
179
20000/20000 [==============================] - 1s 52us/sample
180
20000/20000 [==============================] - 1s 53us/sample
181
20000/20000 [==============================] - 1s 53us/sample
182
20000/20000 [==============================] - 1s 54us/sample
183
20000/20000 [==============================] - 1s 54us/sample
184
20000/20000 [==============================] - 1s 55us/sample
185
20000/20000 [==============================] - 1s 53us/sample
186
20000/20000 [==============================] - 1s 56us/sample
187
20000/20000 [==============================] - 1s 54us/sample
188
20000/20000 [==============================] - 1s 54us/sample
189
20000/20000 [==============================] - 1s 53us/sample
190
20000/20000 [==============================] - 1s 53us/sample
191
20000/20000 [==============================] - 1s 53us/sample
192
20000/20000 [==============================] - 1s 53us/sample
193
20000/20000 [==============================] - 1s 54us/sample
194
20000/20000 [==============================] - 1s 53us/sample
195
20000/20000 [==============================] - 1s 53us/sample
196
20000/20000 [==============================] - 1s 55us/sample
197
20000/20000 [==============================] - 1s 54us/sample
198
20000/20000 [==============================] - 1s 56us/sample
199
20000/20000 [==============================] - 1s 55us/sample
200
20000/20000 [==============================] - 1s 53us/sample
201
20000/20000 [==============================] - 1s 54us/sample
202
20000/20000 [==============================] - 1s 54us/sample
203
20000/20000 [==============================] - 1s 54us/sample
204
20000/20000 [==============================] - 1s 54us/sample
205
3316/3316 [==============================] - 0s 85us/sample

TypeError: Tuple or struct_time argument required

In [98]:
prediction=model.predict_classes(train_x,verbose=1)
np.savetxt("testresult20200520_1.csv", prediction, fmt="%d",delimiter=",")

2904/2904 [==============================] - 0s 65us/sample

In [38]:
gc.collect()
dataresult=pd.read_csv('./testdata20200403_split_7/testdata20200403_1.csv',header=0)
print("part1")
prediction = model.predict_classes(dataresult,verbose=1)
np.savetxt("./testresult20200410/testresult20200410_1.csv", prediction, fmt="%d",delimiter=",") 
gc.collect()
dataresult=pd.read_csv('./testdata20200403_split_7/testdata20200403_2.csv',header=0)
print("part2")
prediction = model.predict_classes(dataresult,verbose=1)
np.savetxt("./testresult20200410/testresult20200410_2.csv", prediction, fmt="%d",delimiter=",") 
gc.collect()
dataresult=pd.read_csv('./testdata20200403_split_7/testdata20200403_3.csv',header=0)
print("part3")
prediction = model.predict_classes(dataresult,verbose=1)
np.savetxt("./testresult20200410/testresult20200410_3.csv", prediction, fmt="%d",delimiter=",") 
gc.collect()
dataresult=pd.read_csv('./testdata20200403_split_7/testdata20200403_4.csv',header=0)
print("part4")
prediction = model.predict_classes(dataresult,verbose=1)
np.savetxt("./testresult20200410/testresult20200410_4.csv", prediction, fmt="%d",delimiter=",") 
gc.collect()
dataresult=pd.read_csv('./testdata20200403_split_7/testdata20200403_5.csv',header=0)
print("part5")
prediction = model.predict_classes(dataresult,verbose=1)
np.savetxt("./testresult20200410/testresult20200410_5.csv", prediction, fmt="%d",delimiter=",")

KeyboardInterrupt: